name: Analyze SolarTineMS Repository

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: breakcraft/SolarTineMS
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests pandas

      - name: Analyze Repository Structure
        run: |
          python -m script.analyze_structure

      - name: Analyze Commits
        run: |
          python -m script.analyze_commits
