name: Scala CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -R

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: 'sbt'

      - name: Set up SBT
        uses: olafurpg/setup-scala@v11
        with:
          sbt-version: '1.5.5'

      - name: Verify SBT files
        run: |
          if [ ! -f build.sbt ]; then echo "Error: build.sbt not found"; exit 1; fi
          if [ ! -f project/build.properties ]; then echo "Error: project/build.properties not found"; exit 1; fi
          if [ ! -d project ]; then echo "Error: project directory not found"; exit 1; fi

      - name: Run tests
        run: sbt test

      - name: Upload dependency graph
        uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
