name: Split and Consolidate File

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  split_and_consolidate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests

      - name: Retrieve File and Process
        run: |
          import requests

          def split_file(content, chunk_size=1024):
              return [content[i:i + chunk_size] for i in range(0, len(content), chunk_size)]

          def save_chunks(chunks, base_name='chunk'):
              paths = []
              for i, chunk in enumerate(chunks):
                  chunk_path = f'{base_name}_{i+1}.txt'
                  with open(chunk_path, 'w', encoding='utf-8') as file:
                      file.write(chunk)
                  paths.append(chunk_path)
              return paths

          def consolidate_chunks(chunk_paths, output_path='consolidated.txt'):
              with open(output_path, 'w', encoding='utf-8') as output_file:
                  for chunk_path in chunk_paths:
                      with open(chunk_path, 'r', encoding='utf-8') as chunk_file:
                          output_file.write(chunk_file.read())

          url = "https://raw.githubusercontent.com/breakcraft/SolarTineMS/master/src/main/java/net/server/Server.java"
          response = requests.get(url)
          file_content = response.text

          chunks = split_file(file_content, chunk_size=1024)
          chunk_paths = save_chunks(chunks)

          for path in chunk_paths:
              print(f'Chunk created: {path}')

          consolidate_chunks(chunk_paths, output_path='Server_Consolidated.java')
          print(f'Consolidated file created: Server_Consolidated.java')

        shell: python
